version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - demo

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - demo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - demo

volumes:
  pgdata:

networks:
  demo:
